import os
os.chdir("..")
os.chdir("..")
os.mkdir("papka1")
os.chdir("papka1")
print(os.getcwd())
q= open("test_1.txt","w")
q.write(" ")
q.close()
w= open("test_2.txt","w")
w.write(" ")
w.close()
e= open("test_3.txt","w")
e.write(" ")
e.close()
os.rename("test_1.txt","rename_1.txt")
os.rename("test_2.txt","rename_2.txt")
os.rename("test_3.txt","rename_3.txt")
os.remove("rename_1.txt")
os.remove("rename_2.txt")
os.remove("rename_3.txt")
os.chdir("..")
print(os.getcwd())
os.removedirs("papka1")


